from utilities import start_tests, WebLink, AudioLink

from utilities import WordType, WordNote, PronNote, BookPage, Level, Item, process_dictionary, find_random_answers, \
    start_tests, Gender

# sloveno, traduzione, tipo, note, unità

enota = {}


enota[1] = (
    ("enota", "unità"),
    ("plačati", ("pagare", "saldare", "liquidare"), WordType.VERB, WebLink("https://it.glosbe.com/sl/it/pla%C4%8Dati"), AudioLink("https://glosbe.com/fb_aud/mp3/dB4896222_audio-by-183515.mp3")),
    ("plačam", "io pago"),
    ("plačaš", "tu paghi"),
    ("plača", "lui paga"),
    ("plačamo", "noi paghiamo"),
    ("plačate", "voi pagate"),
    ("plačajo", "loro pagano"),
    ("moram plačati najemnino", "Devo pagare l'affitto"),
    ("moram plačati", "devo pagare"),
    ("moram", "devo"),
    ("najemnina", "affitto"),
    ("plačilo", "pagamento", WebLink("https://it.glosbe.com/sl/it/pla%C4%8Dilo")),
    ("plačljiv", "pagabile"), # "a pagamento"
    ("slovar", "dizionario"),
    ("svet", "mondo"),
    ("svetovati", "consigliare", WordType.VERB),
    ("svetovalec", "consigliere"),
    ("dnevne novice", "notizie del giorno"),
    ("dnevnik", "diario"), # "giornale"
    ("a veste?", "lo sapete?"),
    ("kriza", "crisi"),
    ("plača", "stipendio", WebLink("https://app.glosbe.com/audio/166556:0002382616"), AudioLink("https://glosbe.com/fb_aud/mp3/e22382616_audio-by-166556.mp3")),
    ("kaj", "cosa"),
    ("vaš", "vostro"),
    ("beseda", "parola"),
    ("besedilo", "testo"),
    ("če ste spregledali", "se avete perso", WebLink("https://it.glosbe.com/sl/it/%C4%8De%20ste%20spregledali")),
    ("Ne najdem besed", "Non trovo le parole", WebLink("https://it.glosbe.com/sl/it/Ne%20najdem%20besed")),
    ("najdem", "trovo"),
    ("najti", "trovare", WordType.VERB),
    ("najdeš", "trovi"),
    ("najde", "lui trova"),
    ("najdemo", "troviamo"),
    ("najdete", "trovate"),
    ("najdejo", "trovano"),
    ("najti delo", "trovare lavoro"),
    ("novica", ("notizia", "novità"), WebLink("https://it.glosbe.com/sl/it/novica")), # "novità"
    ("novice", "notiziario", WebLink("https://it.glosbe.com/sl/it/novice")),
    ("prenos", "trasmissione", WebLink("https://it.glosbe.com/sl/it/prenos")), # trasferimento, cessione
    # 20230926
    ("denarnica", "portafoglio"), # preso da altro libro
    ("denar", "denaro"),
    ("kreditna kartica", "carta di credito"),
    ("oprosti, je to tvoja denarnica?", "scusi, è il tuo portafoglio?"),
    ("neurje", ("temporale", "tempesta")),
    # https://www.rainews.it/tgr/fjk/articoli/2023/09/libija-neurje-daniel-povzrocil-3000-mrtvih-in-10000-pogresanih-f725fca7-fe65-47d6-8e65-70a4a784f814.html
    ("nevihta", "temporale"),
    ("neurje povzročilo mrtvih in pogrešanih", "la tempesta ha causato morti e dispersi"),
    ("povzročiti", "causare"),
    ("povzročil", "causato"),
    ("pogrešani", "dispersi"),
    # ("pogrešan", "disperso"),
    # ("pogrešana", "dispersa"),
    # ("pogrešano", "disperso"),
    ("pogrešana oseba", "persona dispersa"),
    ("oseba", "persona"),
    ("pogrešati", ("mancare", "perdere", "sentire la mancanza"), WebLink("https://it.glosbe.com/sl/it/pogre%C5%A1ati")),
    ("pogrešam te", "mi manchi"),
    ("pogrešam", "mi mancano"),
    ("pogrešal", "mancato"),
    # ("pogrešala", "mancata"),
    # ("pogrešalo", "mancato"),
    # ("pogrešali", "mancato"),
    ("ni za kaj", "non c'è di che"),
    ("izvoli", ("prego", "ecco"), WebLink("https://it.glosbe.com/sl/it/izvoli")),
    ("kaj je vidite?", "cosa vedete?"),
    ("kaj vidite?", "cosa vedete?"),
    ("kaj vidim?", "cosa vedo?"),
    ("kaj vidite zdaj?", "cosa vedete adesso?"),
    ("kaj vidim zdaj?", "cosa vedo adesso?"),
    ("knjiga", "libro"),
    ("ti bereš knjigo", "tu leggi un libro"),
    ("on bere knjigo", "lui legge un libro"),

    ("Henrik prihaja iz finske", "Henrik viene dalla Finlandia"),
    ("on je iz Finske", "lui viene dalla finlandia"),
    ("Eno leto bo živel v Sloveniji", "Vivrà in Slovenia per un anno"),
    ("kaj je povedal Martin?", "cosa ha detto Martin?"), # pag. 7

    ("povedal", ("detto", "raccontato")),
    ("Kaj sem ti povedal?","Cosa ti ho detto?", AudioLink("https://app.glosbe.com/audio/166556:0002383245")),
    ("povedati", "dire", WordType.VERB, WebLink("https://it.glosbe.com/sl/it/povedati"), AudioLink("https://app.glosbe.com/audio/166556:0002384100")),

    ("to je enostavno povedati", "è facile da dire", AudioLink("https://app.glosbe.com/audio/166556:0002384100")),

    ("nekdo prihaja", "qualcuno sta arrivando"),
    ("nekdo", "qualcuno"),
    ("prihajati", ("venire", "arrivare"), WebLink("https://it.glosbe.com/sl/it/prihajati")),
    ("prihajam", "io arrivo"),
    ("prihajaš", "tu arrivi"),
    ("prihaja", "arriva", WebLink("https://it.glosbe.com/sl/it/prihaja")),

    # slovenska beseda C Zivo 1b Sb, pag. 7

    ("vi zdaj stanuje tukaj?", "adesso abitate qui?"),
    ("kje stanujete?", "dove abitate?"),
    ("kje živite?", "dove vivete?"),
    ("kje živiš?", "dove vivi?"),
    ("kje živiš zdaj?", "dove vivi adesso?"),
    ("kje", "dove", WebLink("https://it.glosbe.com/sl/it/kje")),
    ("tukaj stanujem", "Abito qui"),
    ("tukaj živim", "Vivo qui"),
    ("tukaj živim zdaj", "Vivo qui adesso"),

    ("zdaj", ("adesso", "d'ora in poi", "ora"), WebLink("https://it.glosbe.com/sl/it/zdaj")),
    ("jaz sem soseda iz prvega nadstropja", "io sono la vicina del primo piano"),
    ("jaz sem sosed", "io sono il vicino"),
    ("iz", "da", WebLink("https://it.glosbe.com/sl/it/iz")),

    ("prvi", ("primo", "capo", "principale"), WebLink("https://it.glosbe.com/sl/it/prvi"), AudioLink("https://app.glosbe.com/audio/166556:0002384029")),
    ("prvo nadstropje", "primo piano", WebLink("https://it.glosbe.com/sl/it/prvo%20nadstropje")),
    ("kavarna", ("caffetteria", "bar"), WebLink("https://it.glosbe.com/sl/it/kavarna")),

    ("kakšen", ("quali", "che tipo di"), WebLink("https://it.glosbe.com/sl/it/kak%C5%A1en")), # pag. 11
    ("glagoli", "verbi"),
    ("delati", "lavorare", WordType.VERB),
    ("delam", "io lavoro", ),
    ("hoditi", "andare", WordType.VERB),
    ("hodim", "io vado", ),
    ("pisati se", "chiamarsi", WordType.VERB),
    ("pišem se", "mi chiamo", ),
    ("podpisati se", "firmare", WordType.VERB),
    ("podpišem se", "io firmo"),
    ("potrebovati", "avere bisogno di", WordType.VERB),
    ("potrebujem", "io ho bisogno di"),
    ("roditi se", "nascere", WordType.VERB),
    ("rodim se", "io nasco"),
    ("spoznati", "conoscere", WordType.VERB, WebLink("https://it.glosbe.com/sl/it/spoznati")),
    ("spoznam", "io conosco"),
    ("srečanje", ("incontro", "riunione", "convegno"), WebLink("https://it.glosbe.com/sl/it/sre%C4%8Danje")),
    ("srečati", "incontrare", WordType.VERB),
    ("srečam", "io incontro"),
    ("stanovati", "abitare", WordType.VERB),
    ("stanujem", "io abito"),
    ("študirati", "studiare", WordType.VERB),
    ("študiram", "io studio"),
    ("živeti", "vivere", WordType.VERB),
    ("v živo", "dal vivo"),
    ("živim", "io vivo"),
    ("mlad", "giovane", WordType.ADJECTIVE),
    ("star", "vecchio", WordType.ADJECTIVE),
    ("zaposlen", ("impiegato", "occupato", "impegnato"), WebLink("https://it.glosbe.com/sl/it/zaposlen")),
    ("upokojenec", "pensionato"),
    ("upokojenka", "pensionata"),
    ("študent", "studente"),
    ("študentka", "studentessa"),
    ("visok", "alto"),
    ("velik", "grande"),
    ("majhen", "piccolo"),
    ("suh", "magro"),
    ("debel", "grasso"),
    ("lep", "bello"),
    ("dober", "buono"),
    ("prijazen", "gentile"),
    ("neprijazen", "scortese"),
    ("oči", "occhi"),
    ("lasje", "capelli"),
    ("brada", "barba"),
    ("očala", "occhiali"),
    ("naš", ("nostro", "il nostro", ), WebLink("https://it.glosbe.com/sl/it/na%C5%A1")),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("hočeš", "tu vuoi"),
    ("kaj hočeš študirati? ", "cosa vuoi studiare?"),
    ("študiral je medicino", "ha studiato medicina"),
    ("ime", "nome"),
    ("priimek", "cognome"),
    ("gospod", "signore"),
    ("gospa", "signora"),
    ("spol", "genere"),
    ("moški", "uomo"),
    ("ženski", "donna"),
    ("datum rojstva", "data di nascita"),
    ("kraj rojstva", "luogo di nascita"),
    ("rojstni dan", "compleanno"),
    ("naslov", "indirizzo"),
    ("ulica", "via"),
    ("hišna številka", "numero civico"),
    ("poštna številka", "codice postale"),
    ("kraj", ("posto", "luogo", "posizione")),
    ("mesto", "città"),
    ("država", "stato"),
    ("naordnost", "nazionalità"),
    ("poklic", "professione"),
    ("služba", "lavoro"),
    ("zaklad", ("tesoro", "gioiello"), WebLink("https://it.glosbe.com/sl/it/zaklad")),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),

    ("kakšen glagol je to?", "che tipo di verbo è questo?"),
    ("osebna identiteta", "identità personale"),
    ("osebna", "personale"),
    ("osebni", "personali"),


    ("kakšna je tvoja osebna identiteta?", "qual è la tua identità personale?"),
    # ("oseba", "persona"),
    ("besedni zaklad", "lessico"),
    ("družina", "famiglia"),
    ("", ""),
    ("", ""),
    ("", ""),

    ("me veseli", "piacere"),
    ("a bobne igrate", ("suonate la batteria?", "ma suoni la batteria")),
    ("veste, tukaj je ob desetih zvecer mir", "sapete, qui alle dieci di sera c'è silenzio"),
    ("tukaj", "qui"),
    ("seveda", ("certo", "ovviamente")),
    ("mir", ("silenzio", "pace", "tranquillità")),
    ("je ob desetih","è alle dieci"),
    ("zvecer", "di sera"),
    ("ob", "alle"),
    ("ob desetih", "alle dieci"),
    ("ob desetih zvecer", "alle dieci di sera"),
    ("rada imam mir", "mi piace la tranquillità"),
    ("rada", "a lei piace"),
    ("veste", "sapete"),
    ("da imamo novega soseda", "(che) abbiamo un nuovo vicino"),
    ("Henrik igra bobne", "Henrik suona la batteria"),
    ("zakaj", ("perché", "per quale motivo", "per quale ragione"), WebLink("https://it.glosbe.com/sl/it/zakaj")),
    ("zakaj igra bobne?", "perché suona la batteria?"),
    ("zakaj igraš bobne?", "perché suoni la batteria?"),
    ("zakaj me ne poslušaš?", "perché non mi ascolti?"),
    ("martin se uči slovenščine", "martin sta imparando lo sloveno"),
    ("on se uči", "sta imparando"),
    ("govoriti", "parlare"),
    ("pogovarjati", "parlare"), # dialogare, interagire  # ???
    ("odgovor", "risposta"),
    ("odgovoriti", "rispondere"),
    ("katere jezike govoriš?", "quali lingue parli?"),
    ("katere", "quali"),
    ("katere jezike", "quali lingue"),
    ("katere jezike govoriš zdaj?", "quali lingue parli adesso?"),
    ("jezik", ("lingua", "linguaggio", "idioma"), WebLink("https://it.glosbe.com/sl/it/jezik")),


    ("delovni zvezek", "Quaderno di lavoro"),
    ("ucbenik", "libro di testo"),
    ("otrok", "bambino"),
    ("sin", "figlio"),
    ("hčerka", "figlia"),
    ("osebna izkaznica", "carta d'identità"),
    ("potni list", "passaporto"),
    ("obrazec", "modulo"),
    ("poročen", "sposato"),
    ("predstavite se", "presentarsi"),
    ("kdo je sto?", "chi è questo?"),
    ("to je Martin", "questo è Martin"),
    ("z", "con"),
    ("vi ste naš sosed", "voi siete il nostro vicino"),
    ("tukaj bom živei eno leto", "vivrò qui per un anno"),
    # ("živei eno leto", "vivrò un anno"),
    ("živel bom", "io vivrò"),
    ("živijo", "ciao", WebLink("https://it.glosbe.com/sl/it/%C5%BEivijo")),
    ("vi pa niste", "voi invece non siete"),
    ("od kod ste?", "da dove venite?"),
    ("kaj pa je to?", "e cosa è questo?"),
    ("so to bobni?", "questi sono tamburi?"),
    ("res?", ("davvero?", "veramente?")),
    ("bobne igram za hobi", "suono la batteria per hobby"),
    ("všeč mi je jazz", "mi piace il jazz"),
    ("ti ni všeč?", "non ti piace?"),
    ("vam lahko pomagam?", "posso aiutarvi?"),
    ("všeč mi je", "mi piace"),
    ("na inštitutu delam kot raziskovalec", "all'istituto lavoro come ricercatore"),
    ("zelo ste prijazni", "siete molto gentile"),
    ("zelo", "molto"),
    ("v katero nadstropje greva?", "a quale piano andiamo?"),
    ("na hodniku", "nel corridoio"),
    ("odgovor", ("risposta", "soluzione", "replica"), WebLink("https://it.glosbe.com/sl/it/odgovor")),
    ("v drugo", "al secondo"),
    ("a pridete zvečer na pijačo?", "e venite a bere qualcosa stasera?"),
    ("Tina in jaz živiva zgorai", "io e Tina viviamo al piano di sopra"),
    ("stanovanje", "appartamento"),
    ("pridem", "io vengo"),
    ("hvala še enkrat", "grazie ancora"),
    ("dopolnite", "completate"),
    ("prihaja", "sta arrivando"),
    ("v Sloveniji bo živel eno leto", "in Slovenia vivrà un anno"),
    ("všeč mu je glasba", "gli piace la musica"),
    ("za hobi igra bobne", "per hobby suona la batteria"),
    ("po poklicu je fizik", "di professione è fisico"),
    ("preberite", "leggete"),
    ("jaz študiram glasbo", "io studio musica"),
    ("ste vi tudi glasbenik?", "anche voi siete musicisti?"),
    ("tudi", "anche"),
    ("glasba", "musica", WebLink("https://it.glosbe.com/sl/it/glasba")),
    ("ko vidi bobne", "quando vede la batteria"),
    ("se takoj začne pogovarjati", "inizia subito a parlare"),
    # č š ž
    ("začne", "lui inizia"),
    ("se začne pogovarjati", "inizia a parlare"),
    ("novega soseda povabi na na pijačo", "invita il nuovo vicino a bere qualcosa"),
    ("povabi na pijačo", " lui invita a bere qualcosa"),
    ("ali", "o"),
    ("kakšna je vaša hiša?", "com'è la vostra casa?"),
    ("kakšna je vaš blok?", "com'è il vostro palazzo?"),
    ("kdo so vaši sodedi?", "chi sono i vostri vicini?"),
    ("kakšni so vaši sodedi?", "come sono i vostri vicini?"),
    ("mislim", "penso"),
    ("bomo dobili novega sodeda", "avremo un nuovo vicino"),
    ("sosed", "vicino"),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
)


def run_me():
    dict_slo, dict_ita = process_dictionary(enota)

    number_of_answers = 10

    print("1 - test da sloveno a italiano")
    print("2 - test da italiano a sloveno")
    data = input("risposta (q per uscire): ")
    if data is None or data == "q":
        return
    elif data == "1":
        start_tests(dict_slo, number_of_answers=number_of_answers)
    elif data == "2":
        start_tests(dict_ita, slo2ita=False, number_of_answers=number_of_answers)
    else:
        print("risposta non valida")


if __name__ == "__main__":
    run_me()
