from utilities import WordType, WordNote, PronNote, BookPage, Level, Item, process_dictionary, find_random_answers, \
    start_tests, Gender

enota = {}

# č š ž

enota["enota 5"] = (

    ("kakšno pico imate radi?", "che tipo di pizza vi piace?"),
    ("kakšno pico imaš rad/a?", "che tipo di pizza ti piace?"),
    ("kakšen sendvič imaš rad/a?", "che tipo di panino ti piace?"),
    ("potem", "dopo"),
    ("kam greš?", "dove vai?"),
    ("od kod si?", "da dove arrivi/di dove sei?"),
    ("sem iz Trsta", "vengo da Trieste", Gender.MALE),
    ("sem iz Italije", "vengo dall'Italia", Gender.FEMALE),
    ("grem v Trst", "vado a Trieste", Gender.MALE),
    ("grem v italijo", "vado in Italia", Gender.FEMALE),
    ("sem iz Celja", "sono di Celje", Gender.NEUTRAL),
    ("grozdje", "uva"),
    ("jabolko", "mela"),
    ("jagoda", "fragola"),
    ("pomaranča", "arancia"),
    ("čebula", "cipolla"),
    ("korenje", "carote"),
    ("krompir", "patata"),
    ("paprika", "peperone"),
    ("paradižnik", "pomodoro"),
    ("solata", "lattuga"),
    ("čips", "patatine"),
    ("čokolada", "cioccolata"),
    ("jajce", "uovo"),
    ("jogurt", "yogurt"),
    ("kruh", "pane"),
    ("meso", "carne"),
    ("mleko", "latte"),
    ("riba", "pesce"),
    ("salama", "salame"),
    ("sendvič", "panino"),
    ("sir", "formaggio"),
    ("sladoled", "gelato"),
    ("špageti", "spaghetti"),
    ("Predjedi", "Antipasti"),
    ("Juhe", "Brodi/zuppe"),
    ("Glavne jedi", "Secondo piatto"),
    ("Priloge", "Contorni"),
    ("Solate", "Insalate"),
    ("Sladice", "Dolci"),
    ("Oprostite, kje imate …?", "Mi scusi, dove avete…?"),
    ("tam", "là"),
    ("na levi", "a sinistra"),
    ("na desni", "a destra"),
    ("tam, na levi", "là, a sinistra"),
    ("tam, na desni", "là, a destra"),
    ("Tukaj", "qua"),
    ("Še kaj?", "ancora qualcosa?"),
    ("Lahko pomagam?", "posso aiutare?"),
    ("samo gledam", "soltanto guardo"),
    ("Gotovina ali kartica?", "contanti o carta?"),
    ("Želite, prosim?", "desidera, prego?"),
    ("prosim, 20 dek", "prego, 2 etti"),
    ("prosim, pol kile", "prego, mezzo chilo"),
    ("prosim, eno kilo", "prego, un chilo"),
    ("Glagoli", "verbi"),
    ("Dobiti", "ricevere"),
    ("dobim", "ricevo"),
    ("Imeti", "avere"),
    ("Kupiti", "comprare"),
    ("Naročiti", "Ordinare"),
    ("Plačati", "Pagare"),
    ("Želeti", "Desiderare"),
    ("imam", "io ho"),
    ("kupim", "io compro"),
    ("naročim", "io ordino"),
    ("plačam", "io pago"),
    ("želim", "io desidero"),
    ("V restavraciji", "al ristorante"),
    ("A imate …? Ne, žal nimamo", "Avete …? – No, purtroppo non l’abbiamo"),
    ("Jedilni list, prosim. Izvolite", "La lista dei piatti, per favore. Ecco qui"),
    ("Izvolite", "ecco qui"),
    ("Oprostite, to ni v redu. Jaz želim…", "Mi scusi, questo non è a posto. Io desidero…"),
    ("Žal mi je. Takoj dobite…", "Mi dispiace. Subito avrà/avrete (Le portiamo)…"),
    ("A lahko plačam?", "Posso pagare?"),
    ("S kartico ali z gotovino?", "Con carta o con contanti?"),
    ("Želite še sladico?", "Desidera anche il dolce?"),
    ("Samo", "soltanto"),
    ("Gospod natakar, moj račun ni v redu", "Sig. cameriere, il mio conto non è a posto"),
    ("Joj, oprostite, to ni vaš račun", "Oh, scusi (scusate), questo non è il suo (vostro) conto"),
    ("Ne morem več", "Non (ne) posso più. /Sono a posto/"),
    ("Žal mi je", "mi dispiace"),
    ("hrana", "cibo"),
    ("pijača", "bevanda"),
    ("hrana in pijača", "cibo e bevande"),
    ("trgovina", "negozio"),
    ("restavracija", "ristorante"),
    ("slovnica", "grammatica"),
    ("kaj kupimo?", "cosa compriamo?"),
    ("v nedeljo grem ...", "domenica vado ..."),
    ("kaj gres nedelja?", "dove vai domenica?"), # check!!!
    ("oprostite, kie imate kruh?", "scusi, dove tenete il pane?"),
    ("prodajalka", "commessa"),
    ("vrečko, prosim", "sacchetto, per favore"),
    ("koliko stane to vino?", "quanto costa questo vino?"),
# č š ž
    ("Želite?", "desidera?"),
    ("kaj kupiš v trgovini?", "cosa compri nel negozio?"),
    ("grem po solato in kruh", "vado a prendere insatala e pane"),
    ("vceraj", "ieri"),
    ("vceraj sem šel po sestro", "ieri sono andato a trovare la sorella"),
    ("slovenska tradicionalna hrana", "cibo tradizionale sloveno"),
    ("kranjska klobasa", "Salsiccia Kranjska"),
    ("kremšnita", "crema carsolina"),
    ("potica", "putizza"),
    ("prekmurska gibanica", "dolce dessert del prekmurje"),
    # ("žganci", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),

)


def run_me():
    dict_slo, dict_ita = process_dictionary(enota)

    print("1 - test da sloveno a italiano")
    print("2 - test da italiano a sloveno")
    data = input("risposta (q per uscire): ")
    if data is None or data == "q":
        return
    elif data == "1":
        start_tests(dict_slo)
    elif data == "2":
        start_tests(dict_ita, slo2ita=False)
    else:
        print("risposta non valida")


if __name__ == "__main__":
    run_me()
