from utilities import WordType, WordNote, PronNote, BookPage, Level, \
    Gender, WebLink, AudioLink, generic_run_me, QuestionGroup

# sloveno, traduzione, tipo, note, unità

enota = {}

enota["enota: dober dan"] = (
    ("enota", "unità"),
    ("dober dan", "buongiorno", BookPage(7)),
    ("in", "e", WordType.CONJUNCTION, Level.EASY),
    ("črkujte", "sillabare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("dopolnite", "completare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("napišite", "scrivere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("odgovorite", "rispondere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("poslušajte", "ascoltare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("ponovite", "ripetere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("ponavljanje", "ripetizione", WordType.NOUN, Level.DIFFICULT, QuestionGroup("verbo")),
    ("preberite", "leggere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("sestavite besede", "compilate le parole", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),  # ???
    ("vprašajte in odgovorite", "chiedete e rispondete", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("vprašajte", "chiedete", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("vstavite", "inserire", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("preberite in dopolnite", "leggere e completare", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("poslušajte in ponovite", "ascoltare e ripetere", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("poslušajte in napišite pet besed", "ascolta e scrivi cinque parole", WordType.VERB, Level.DIFFICULT, QuestionGroup("verbo")),
    ("uporabljam avto", "io uso l'auto", QuestionGroup("verbo")),
    ("besedišče", "vocabolario"),
    ("beseda", "parola"),
    ("besede", "parole"),
    ("črko", "lettera"),
    ("eno črko lahko uporabite večkrat", "puoi usare una lettera più di una volta"),
    ("eno črko", "una lettera"),
    ("lahko", "può"),
    ("uporabite", "usare", QuestionGroup("verbo")),
    ("lahko sedim?", "posso sedere?", AudioLink("https://app.glosbe.com/audio/183515:0004895993"), QuestionGroup("domanda")),
    ("lahko vstanem?", "posso alzarmi?", QuestionGroup("domanda")),
    ("lahko grem?", "posso andare?", QuestionGroup("domanda")),
    ("lahko grem na stranišče?", "posso andare in bagno?", QuestionGroup("domanda")),
    ("lahko grem na sprehod?", ("posso fare una passeggiata?", "posso fare un giro?"), QuestionGroup("domanda")),
    ("Lahko prosim odidemo?", "Possiamo andare, per favore?", AudioLink("https://app.glosbe.com/audio/166556:0002382101"), QuestionGroup("domanda")),
    ("večkrat", "parecchie volte"),
    ("lahko uporabite", "puoi usare", QuestionGroup("verbo")),
    ("identiteta", "identità"),
    ("abeceda", "alfabeto"),
    ("številka", "numero", Gender.FEMALE),  # genere femminile
    ("številke", "numeri", Gender.FEMALE),
    ("države", "stati"),
    ("poklici", "professioni"),
    ("poklic", ("professione", "mestiere", "occupazione"), WebLink("https://it.glosbe.com/sl/it/poklic")),
    ("jeziki", "le lingue"),
    ("slovnica", "grammatica"),
    ("biti", "essere", WordType.VERB, WordNote("infinito"), QuestionGroup("verbo")),
    ("govoriti", "parlare", WordType.VERB, WordNote("infinito"), QuestionGroup("verbo")),
    ("jaz sem Marco", "io sono Marco", WordType.SENTENCE),
    ("me veseli!", "piacere", WordType.SENTENCE),
    ("živjo", "ciao"),
    ("adijo", "ciao"),
    ("dober večer", "buonasera"),
    ("lahko noč", "buona notte"),
    ("se vidimo", "ci vediamo"),
    ("dobro jutro", "buon mattino"),
    ("nasvidenje", "arrivederci"),
    ("lep dan", "buona giornata"),
    ("pozdravljeni", "piacere/io vi saluto", WordNote("dober dan in pozdravljeni")),
    ("kako si?", "come stai? (come sei?)", WordNote("letterale: come sei?"), QuestionGroup("domanda")),
    ("dobro", "bene", WordType.ADVERB),
    ("odlično", "eccellente", WordNote("kako si? odlično!")),
    ("slabo", "male", WordNote("kako si? slabo")),
    ("tako tako", "così così"),
    ("v redu", "ok"),
    ("zelo dobro", "molto bene", WordType.ADVERB),
    ("zelo", "molto"),
    ("avto", "automobile"),
    ("april", "aprile"),
    ("avgust", "agosto"),
    ("banka", "banca"),
    ("balkon", "balcone"),
    ("cigareta", "sigaretta"),
    ("center", "centro"),
    ("C-vitamin", "vitamina C"),
    ("čokolada", "cioccolato"),
    ("čips", "patatine"),
    ("čaj", "tè"),
    ("december", "dicembre"),
    ("direktor", "direttore"),
    ("dinozaver", "dinosauro"),
    ("Evropa", "Europa"),
    ("evro", "euro"),
    ("evrov", "euro (plurale)"),
    ("elektrika", "elettricità"),
    # film, festival
    ("februar", "febbraio"),
    ("galerija", "galleria d'arte"),
    ("garaža", "garage"),
    ("hvala", "grazie"),
    ("informacija", "informazione"),
    ("inštitut", "istituto"),
    ("januar", "gennaio"),
    ("junij", "giugno"),
    ("julij", "luglio"),
    ("ja", "si"),
    ("kava", "caffè"),
    ("kitara", "chitarra"),
    ("koncert", "concerto"),
    ("limona", "limone"),
    ("limonada", "limonata"),
    ("marec", "marzo", PronNote("c finale come z")),
    ("maj", "maggio"),
    ("muzej", "museo"),
    ("november", "novembre"),
    ("noč", "notte"),
    ("ne", "no"),
    ("oktober", "ottobre"),
    ("opera", "musica lirica"),
    ("pica", "pizza"),
    ("policija", "polizia"),
    ("park", "parco/giardino"),
    ("restavracija", "ristorante"),
    ("recepcija", "ricezione"),
    ("riž", "riso"),
    ("sendvič", "sandwitch"),
    ("solata", "insalata"),
    ("september", "settembre"),
    ("šola", "scuola"),
    ("špageti", "spaghetti"),
    ("telefon", "telefono"),
    ("tehnologija", "tecnologia"),
    ("tenis", "tennis"),
    ("univerza", "università"),
    ("ura", "ora"),
    ("učiti se", "imparare"),
    ("voda", "acqua"),
    ("veterinar", "veterinario"),
    ("zdravnik", "medico"),
    ("žirafa", "giraffa"),
    ("kaj je ...?", "cosa è ...?", QuestionGroup("domanda")),
    ("Kaj to pomeni?", "Cosa significa questo?", QuestionGroup("domanda") ),
    ("kako se reče ...?", "come si dice ...?", QuestionGroup("domanda")),
    ("oprostite", "mi scusi"),
    ("oprostite, ne razumem", "mi scusi, non capisco"),
    ("ne razumem", "non capisco"),
    ("ponovite, prosim", "ripeti, per favore"),
    ("prosim", "per favore"),
    ("nič", "0", WordType.NUMBER),
    ("ena", "1", WordType.NUMBER),
    ("dve", "2", WordType.NUMBER),
    ("tri", "3", WordType.NUMBER),
    ("štiri", "4", WordType.NUMBER),
    ("pet", "5", WordType.NUMBER),
    ("šest", "6", WordType.NUMBER),
    ("sedem", "7", WordType.NUMBER),
    ("osem", "8", WordType.NUMBER),
    ("devet", "9", WordType.NUMBER),
    ("deset", "10", WordType.NUMBER),
    ("enajst", "11", WordType.NUMBER),
    ("dvanajst", "12", WordType.NUMBER),
    ("trinajst", "13", WordType.NUMBER),
    ("štirinajst", "14", WordType.NUMBER),
    ("dvajset", "20", WordType.NUMBER),
    ("enaindvajset", "21", WordType.NUMBER),
    ("trideset", "30", WordType.NUMBER),
    ("sto", "100", WordType.NUMBER),
    ("tisoč", "1000", WordType.NUMBER),
    ("milijon", "1.000.000", WordType.NUMBER),
    ("a mi daš telefonsko številko, prosim?", "mi dai il numero di telefono, per favore?", QuestionGroup("domanda")), # telefonsko številko: accusativo
    ("moja telefonska številka je ...", "il mio numero di telefono è ..."),
    ("koliko", "quanto"),
    ("koliko si star/a?", "quanti anni hai?", QuestionGroup("domanda")), #  (quanto sei vecchio)
    ("star/a sem oseminštirideset let", "io ho 48 anni"),
    ("leta", "anni"),
    ("koliko stane pica?", "quanto costa la pizza?", QuestionGroup("domanda")),
    ("pica stane pet evrov", "la pizza costa cinque euro"),
    ("to je poceni", "questo costa poco"),
    ("to je predrago", "questo è troppo caro"),
    ("poceni", "a buon mercato"),
    ("naslov", "indirizzo"),
    ("a mi daš naslov, prosim?", "mi dai l'indirizzo, per favore?", QuestionGroup("domanda")),
    ("a mi daš email, prosim?", "mi dai l'email, per favore?", QuestionGroup("domanda")),
    ("pika", ". (punto)"),
    ("afna", "@"),
    ("minus", "segno meno"),
    ("črtica spodaj", "linetta sotto"),
    ("od kod si?", "di dove sei/da dove vieni?", QuestionGroup("domanda")),
    ("kdo je to?", "chi è questo?", QuestionGroup("domanda")),
    ("kdo si?", "chi sei tu?", QuestionGroup("domanda")),
    ("sem iz Slovenije, iz Maribora", "(io) vengo (sono) dalla Slovenia, da Maribor"),
    ("Mark je iz Rusije", "Mark viene dalla Russia"),
    ("kaj si po poklicu?", "cosa sei di mestiere/che lavoro fai?", QuestionGroup("domanda")),
    ("po poklicu sem ...", "di mestiere sono ..."),
    ("delam kot ...", "lavoro come ..."),
    ("jaz delam", "io lavoro"),
    # ("studiram ...", "studio ..."),
    ("kaj počneš?", "cosa fai?", QuestionGroup("domanda")),
    # ("kaj delaš?", "cosa fai?"),
    ("kaj študiraš?", "cosa studi?", QuestionGroup("domanda")),
    ("kaj študiraš na univerzi?", "cosa studi all'università?", QuestionGroup("domanda")),
    ("kaj počneš v prostem času?", "cosa fai nel tuo tempo libero?", QuestionGroup("domanda")),
    ("študiram tehniko", "studio ingegneria"),
    ("sošolec", "compagno di classe"),
    ("sošolka", "compagna di classe"),
    ("od kod", "da dove"),
    ("kaj", "che cosa"),
    ("ti si iz Avstrije", "tu vieni dall'Austria"),
    ("vi ste iz Italije", "voi venite dall'Italia"),
    ("drugi dialog", "secondo dialogo"),
    ("inženir", "ingegnere"),
    ("natakar", "cameriere"),
    ("študent", "studente universitario"),
    ("učitelj", "maestro"),
    ("kot", "come"),
    ("inženirka", "ingegnera"),
    ("natakarica", "cameriera"),
    ("študentka", "studentessa universitaria"),
    ("učiteljica", "maestra"),
    ("učiti", "insegnare"),
    ("zdravnica", "medica"),
    ("Peter je inženir", "Peter è un ingegnere"),
    ("katere jezike govoriš?", "quali lingue parli?", QuestionGroup("domanda")),
    ("katere", "quale/i"),
    # ("jezika", "linguaggio/lingue"),
    ("govorim angleško", "io parlo inglese"),
    ("govorim angleško in malo slovensko", "parlo inglese ed un po' di sloveno"),
    ("malo", "poco"),
    ("a govoriš nemško?", "parli tedesco?", QuestionGroup("domanda")),
    ("ja, govorim", "si, lo parlo"),
    ("ne, ne govorim", "no, non lo parlo"),
    ("sem ekonomist", "sono laureato in economia"),
    ("ampak", "ma"),
    ("ampak zdaj ne delam", "ma ora non lavoro"),
    ("zdaj", "ora"),
    ("ime", "nome"),  # IDENTITETA

    ("priimek", "cognome"),
    ("jezik", "linguaggio"),
    ("država", "stato"),
    ("kako ti je ime?", "quale è il tuo nome?", QuestionGroup("domanda")),
    ("kako se pišeš?", "quale è il tuo cognome?", QuestionGroup("domanda")), #  'come ti cognomi'
    ("kolega", "il collega"),
    ("kolegica", "la collega"),
    ("neformalno", "non formale/informale"),
    ("formalno", "formale"),
    ("kako vam je ime?", "(formale) quale è il suo nome?", QuestionGroup("domanda")),
    ("kako se pišete?", "(formale) quale è il suo cognome?", QuestionGroup("domanda")),
    ("od kod ste?", "(formale) da dove viene/di dove è?", QuestionGroup("domanda")),
    ("kaj ste po poklicu?", "(formale) cosa fa di mestiere?", QuestionGroup("domanda")),
    ("koliko ste stari?", "(formale) quanti anni ha?", QuestionGroup("domanda")),
    ("katere jezike govorite?", "(formale) quali lingue parlate?", QuestionGroup("domanda")),
    ("glagol", "verbo"),
    ("jaz sem", "io sono"),  # GLAGOL BITI
    ("ti si", "tu sei"),
    ("on je", "egli è"),
    ("ona je", "lei è"),
    ("mi smo", "noi siamo"),
    ("vi ste", "voi siete"),
    ("oni so", "loro sono"),
    ("one so", "esse sono"),
    ("tudi", ("anche", "inoltre", "peraltro"), WebLink("https://it.glosbe.com/sl/it/tudi"), AudioLink("https://app.glosbe.com/audio/183515:0004896933")),
    ("gospa", "signora"),
    ("gospod", "signore"),
    ("Eva je študentka", "Eva è una studentessa"),
    ("Mark je iz Kanade", "Mark viene dal Canada"),
    ("Jaz sem študent", "Io sono uno studente universitario"),
    ("Sara, Mija in Tjaša so študentke", "Sara, Mija e Tjaša sono studentesse universitarie"),
    ("Tomaž je zdravnik", "Tomaž è un medico"),
    ("Maja, Peter in Nina so iz Slovenije", "Maja, Peter e Nina sono della Slovenia"),
    ("vsi trije so iz Slovenije", "tutti e tre sono dalla Slovenia"),
    ("kdorkoli", "chiunque"),
    ("karkoli", "qualsiasi cosa"),
    ("Mi smo študenti", "noi siamo studenti universitari"),
    ("Gospa Turner, a ste vi iz Avstralije?", "Signora Turner, lei viene dall'Australia?", QuestionGroup("domanda")),
    ("a si ti ekonomist?", "sei laureato in economia?", QuestionGroup("domanda")), # imaš ekonomsko izobrazbo?
    ("jaz nisem", "io non sono"),  # BITI (negativno)
    ("negativno", "negativo"),
    ("ti nisi", "tu non sei"),
    ("on ni", "lui non è"),
    ("ona ni", "lei non è"),
    ("mi nismo", "noi non siamo"),
    ("vi niste", "voi non siete"),
    ("oni niso", "loro non sono"),
    ("one niso", "esse non sono"),
    ("psiholog", "psicologo"),
    ("jaz govorim", "io parlo/sto parlando"),  # GLAGOL: GOVORITI
    ("ti govoriš", "tu parli"),
    ("on govori", "lui parla"),
    ("ona govori", "lei parla"),
    ("mi govorimo", "noi parliamo"),
    ("vi govorite", "voi parlate"),
    ("oni govorijo", "loro parlano"),
    ("one govorijo", "esse parlano"),
    ("a ti govoriš slovensko?", "tu parli sloveno?", QuestionGroup("domanda")),
    ("mobilni telefon", "telefono cellulare", Gender.MALE),
    ("starost", "età"),
    ("učbenik", "libro di testo"),
    ("učenje", "apprendimento", WordType.NOUN),
    ("začetnica", "iniziale", WordType.ADJECTIVE),
    ("slovenščina", "sloveno", WordType.NOUN), # lingua slovena
    ("morje", "mare", WordType.NOUN),
    ("jaz","io"),
    ("vsi", "tutti"),
    ("vse", "tutte"),
    ("prosti čas", "tempo libero"),
    ("čas", "tempo"),
)


if __name__ == "__main__":
    generic_run_me(enota)
