from utilities import generic_run_me

enota = dict()

enota["številke"] = (
    ("nič", "0", ),
    ("ena", "1", ),
    ("dve", "2", ),
    ("tri", "3", ),
    ("štiri", "4", ),
    ("pet", "5", ),
    ("šest", "6", ),
    ("sedem", "7", ),
    ("osem", "8", ),
    ("devet", "9", ),
    ("deset", "10", ),
    ("enajst", "11", ),
    ("dvanajst", "12", ),
    ("trinajst", "13", ),
    ("štirinajst", "14", ),
    ("petnajst", "15", ),
    ("šestnajst", "16", ),
    ("sedemnajst", "17", ),
    ("osemnajst", "18", ),
    ("devetnajst", "19", ),
    ("dvajset", "20",),
    ("enaindvajset", "21",),
    ("dveindvajset", "22",),
    ("triindvajset", "23",),
    ("štiriindvajset", "24",),
    ("petindvajset", "25",),
    ("šestindvajset", "26",),
    ("sedemindvajset", "27",),
    ("osemindvajset", "28",),
    ("devetindvajset", "29",),
    ("trideset", "30", ),
    ("tridesetena", "31",),
    ("tridesetdve", "32",),
    ("tridesettri", "33",),
    ("tridesetštiri", "34",),
    ("tridesetpet", "35",),
    ("tridesetšest", "36",),
    ("tridesetsedem", "37",),
    ("tridesetosem", "38",),
    ("tridesetdevet", "39",),
    ("štirideset", "40", ),
    ("štiridesetena", "41",),
    ("štiridesetdve", "42",),
    ("štiridesettri", "43",),
    ("štiridesetštiri", "44",),
    ("štiridesetpet", "45",),
    ("štiridesetšest", "46",),
    ("štiridesetsedem", "47",),
    ("štiridesetosem", "48",),
    ("štiridesetdevet", "49",),
    ("petdeset", "50", ),
    ("petdesetena", "51",),
    ("petdesetdve", "52",),
    ("petdesettri", "53",),
    ("petdesetštiri", "54",),
    ("petdesetpet", "55",),
    ("petdesetšest", "56",),
    ("petdesetsedem", "57",),
    ("petdesetosem", "58",),
    ("petdesetdevet", "59",),
    ("šestdeset", "60", ),
    ("šestdesetena", "61",),
    ("šestdesetdve", "62",),
    ("šestdesettri", "63",),
    ("šestdesetštiri", "64",),
    ("šestdesetpet", "65",),
    ("šestdesetšest", "66",),
    ("šestdesetsedem", "67",),
    ("šestdesetosem", "68",),
    ("šestdesetdevet", "69",),
    ("sedemdeset", "70", ),
    ("sedemdesetena", "71",),
    ("sedemdesetdve", "72",),
    ("sedemdesettri", "73",),
    ("sedemdesetštiri", "74",),
    ("sedemdesetpet", "75",),
    ("sedemdesetšest", "76",),
    ("sedemdesetsedem", "77",),
    ("sedemdesetosem", "78",),
    ("sedemdesetdevet", "79",),
    ("osemdeset", "80", ),
    ("osemdesetena", "81",),
    ("osemdesetdve", "82",),
    ("osemdesettri", "83",),
    ("osemdesetštiri", "84",),
    ("osemdesetpet", "85",),
    ("osemdesetšest", "86",),
    ("osemdesetsedem", "87",),
    ("osemdesetosem", "88",),
    ("osemdesetdevet", "89",),
    ("devetdeset", "90", ),
    ("devetdesetena", "91",),
    ("devetdesetdve", "92",),
    ("devetdesettri", "93",),
    ("devetdesetštiri", "94",),
    ("devetdesetpet", "95",),
    ("devetdesetšest", "96",),
    ("devetdesetsedem", "97",),
    ("devetdesetosem", "98",),
    ("devetdesetdevet", "99",),
    ("sto", "100",),
    ("stoena", "101",),
    ("stodve", "102",),
    ("stotri", "103",),
    ("stoštiri", "104",),
    ("stopet", "105",),
    ("stošest", "106",),
    ("stosedem", "107",),
    ("stoosem", "108",),
    ("stodevet", "109",),
    ("stodeset", "110",)


)

if __name__ == "__main__":
    generic_run_me(enota)