from utilities import WordType, WordNote, PronNote, BookPage, Level, Item



verbs = {}


verbs["piti"] = (
    ("pijem", "io bevo", WordType.VERB),
    ("piješ", "tu bevi", WordType.VERB),
    ("pije", "egli/lei beve", WordType.VERB),
    ("pijemo", "noi beviamo", WordType.VERB),
    ("pijete", "voi bevete", WordType.VERB),
    ("pijejo", "essi bevono", WordType.VERB),
    ("ne pijem", "io non bevo", WordType.VERB),
    ("ne piješ", "tu non bevi", WordType.VERB),
    ("ne pije", "egli/lei non beve", WordType.VERB),
    ("ne pijemo", "noi non beviamo", WordType.VERB),
    ("ne pijete", "voi non bevete", WordType.VERB),
    ("ne pijejo", "essi/esse non bevono", WordType.VERB),
    ("", ""),

)

verbs[1] = (
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
    ("", ""),
)